In [1]:
import theano as th
from numpy import *

WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: TITAN X (Pascal) (CNMeM is disabled, cuDNN 5110)


In [45]:
x = th.tensor.dmatrix("x")
y = th.tensor.dmatrix("y")
a = array([1,1,1], dtype=th.config.floatX)
k = th.shared(a, borrow=True)
l = th.shared(array([1,1,1], dtype=th.config.floatX))
m = th.shared(array([1,1,1], dtype=th.config.floatX))

In [47]:
out = x ** 2 + k
out += l

In [7]:
import theano 
import theano.tensor as T
from numpy import *
import numpy as np

In [58]:
a = theano.shared(3)
b = theano.shared(3)
outputs = T.as_tensor_variable(ones((2,2)))
o = T.ones((2,2))
result, updates = theano.scan(fn=lambda seq, prior: b + seq + o + prior.dot(1),
                              sequences=T.arange(a),
                              outputs_info=outputs,
                              non_sequences=None,
                              n_steps=None)
updates = [(b, b+1)] + updates
sf7 = theano.function(inputs=[], 
                      outputs=result, 
                      updates=updates)
sf7()
# array([0, 1, 3])

array([[[  5.,   5.],
        [  5.,   5.]],

       [[ 10.,  10.],
        [ 10.,  10.]],

       [[ 16.,  16.],
        [ 16.,  16.]]])

In [60]:
sf7()

array([[[  7.,   7.],
        [  7.,   7.]],

       [[ 14.,  14.],
        [ 14.,  14.]],

       [[ 22.,  22.],
        [ 22.,  22.]]])

In [55]:
print(k.eval())
print(l.eval())
print(m.eval())

b'CudaNdarray([ 3.  3.  3.])'
b'CudaNdarray([ 3.  3.  3.])'
b'CudaNdarray([ 3.  3.  3.])'


In [51]:
a[0] = 50

In [23]:
T.arange(a).eval()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [61]:
from keras import backend as K

Using Theano backend.


In [62]:
input = K.placeholder(shape=(2, 4, 5))
# 以下も動作します:
input = K.placeholder(shape=(None, 4, 5))
# 以下も動作します:
input = K.placeholder(ndim=3)

In [65]:
input.eval(ones((1,2,3)))

AttributeError: 'numpy.ndarray' object has no attribute 'keys'

In [66]:
from keras import backend as K
kvar = K.variable(np.array([[1, 2], [3, 4]]), dtype='float32')
K.eval(kvar)

b'CudaNdarray([[ 1.  2.]\n [ 3.  4.]])'

In [68]:
kvar[:,None]

ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False), (0, 'x')))