In [1]:
import theano
import theano.tensor as T

WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: TITAN X (Pascal) (CNMeM is disabled, cuDNN 5110)


In [4]:
x = T.dvector('x')
y = x ** 2
J, updates = theano.scan(lambda i, y, x: T.grad(y[i], x), sequences=T.arange(y.shape[0]), non_sequences=[y, x])
f = theano.function([x], J, updates=updates)
f([4, 4])

array([[ 8.,  0.],
       [ 0.,  8.]])

In [5]:
x = T.dvector('x')
y = x ** 2
cost = y.sum()
gy = T.grad(cost, x)
H, updates = theano.scan(lambda i, gy,x : T.grad(gy[i], x), sequences=T.arange(gy.shape[0]), non_sequences=[gy, x])
f = theano.function([x], H, updates=updates)
f([4, 4])


array([[ 2.,  0.],
       [ 0.,  2.]])

In [15]:
g = theano.gradient.hessian(cost, x)

In [18]:
T.inv(g).eval({x:[4,4]})

array([[ 0.5,  inf],
       [ inf,  0.5]])

In [19]:
inv

NameError: name 'inv' is not defined

In [22]:
T.invert?

In [32]:
n = T.nlinalg.matrix_inverse(g)

In [33]:
n.eval({x:[4,4]})

array([[ 0.5,  0. ],
       [ 0. ,  0.5]])

In [21]:
import urllib.request
import sys

url = "https://www.dropbox.com/s/xnxtad79ogf7v0a/vgg19.npy?dl=1"
o = urllib.request.urlretrieve(url, "vgg19.npy")

In [23]:

from numpy import *

In [25]:
a = load("vgg19.npy")

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.


In [27]:
pwd

'/home/yu/jupyter/Optimizer_with_theano/Optimizer_with_theano'